In [21]:
def split(im, n):
    _, height = im.shape[:-1]  # W*H
    ndim = height // n
    im = im.reshape(ndim, n, -1, n)  # split in n 2d arrays along cols
    im = im.swapaxes(1, 2)     # restore order: zig-zag
    im = im.reshape(-1, ndim, ndim) # x 2d arrays with dims (n,n)
    return im

In [22]:
import numpy as np

r = np.random.rand(2,4,4)
print(r)
split(r, 2)

[[[0.15959685 0.45476574 0.86139493 0.8448655 ]
  [0.3539857  0.67909059 0.49573629 0.7886483 ]
  [0.06373668 0.39401575 0.23081128 0.61465876]
  [0.08820651 0.11880093 0.83189946 0.42462081]]

 [[0.6378983  0.06928804 0.25111081 0.28865491]
  [0.17049066 0.62269197 0.22005946 0.10167346]
  [0.77934883 0.40463542 0.57577014 0.68466471]
  [0.47896536 0.02329739 0.67403451 0.78549744]]]


array([[[[0.15959685],
         [0.45476574]],

        [[0.06373668],
         [0.39401575]]],


       [[[0.86139493],
         [0.8448655 ]],

        [[0.23081128],
         [0.61465876]]],


       [[[0.3539857 ],
         [0.67909059]],

        [[0.08820651],
         [0.11880093]]],


       [[[0.49573629],
         [0.7886483 ]],

        [[0.83189946],
         [0.42462081]]],


       [[[0.6378983 ],
         [0.06928804]],

        [[0.77934883],
         [0.40463542]]],


       [[[0.25111081],
         [0.28865491]],

        [[0.57577014],
         [0.68466471]]],


       [[[0.17049066],
         [0.62269197]],

        [[0.47896536],
         [0.02329739]]],


       [[[0.22005946],
         [0.10167346]],

        [[0.67403451],
         [0.78549744]]]])