In [2]:
from keras.layers import Input, Conv2D, Lambda
import keras.backend as K
from keras.models import Model

class Reshaper(Model):
    def __init__(self, input_shape, output_shape):
        model_in  = Input(shape=input_shape)
        model_out = K.concatenate((K.variable([-1], dtype='int32'), output_shape))   # arbitrary sampling dim
        shaper = Lambda(lambda x: K.reshape(x, model_out))(model_in)       # apply input to output along (in/out) sampling dim
        super(Reshaper, self).__init__(inputs=model_in, outputs=shaper)

In [5]:
import numpy as np

### Convert 2x3x3 tensor to 6x3 tensor by keeping the order ###

r =np.random.rand(2,3,3)
print(r)
reducer = Reshaper([3,3], [3])
a = reducer(r)
print()
print(a)

[[[0.77162557 0.98728293 0.3656988 ]
  [0.56296166 0.3290901  0.63234192]
  [0.7830633  0.81268121 0.94139804]]

 [[0.78032326 0.17470952 0.40526321]
  [0.27953277 0.05149125 0.56782961]
  [0.80558307 0.13235624 0.68043991]]]

tf.Tensor(
[[0.7716256  0.98728293 0.36569878]
 [0.56296164 0.3290901  0.6323419 ]
 [0.7830633  0.8126812  0.941398  ]
 [0.78032327 0.17470953 0.40526322]
 [0.27953276 0.05149125 0.5678296 ]
 [0.80558306 0.13235624 0.6804399 ]], shape=(6, 3), dtype=float32)
